-intstyle "ise" -incremental -lib "secureip" -o "C:/Users/rayou/Papilio/src/DDS_data_drive_test_isim_beh.exe" -prj "C:/Users/rayou/Papilio/src/DDS_data_drive_test_beh.prj" "work.DDS_data_drive_test" 
